layout_spectrum: 1
color:
  saturation: 1
  brandStrength: 0.6929576
  lightness: 0.3333333
  rhythmicContrast: 0.5769241
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
typography_spectrum: 0.1810036
name: BrianNunes.com
